name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.4.0
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prereleases${increment}"
      id: version
        
    - name: Docker Auth
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build Docker Image
      env:
        IMAGE_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t jjimenezc/docker-graphql:$IMAGE_VERSION .
        docker build -t jjimenezc/docker-graphql:latest .

    - name: Push Docker Image
      env:
        IMAGE_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push jjimenezc/docker-graphql:$IMAGE_VERSION
        docker push jjimenezc/docker-graphql:latest
      
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
